server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    #throw-exception-if-no-handler-found: true #404?? ??
    pathmatch:
      matching-strategy: ant_path_matcher #swagger 3.0 ?? ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  header: Authorization
  secret: c2FjYmFnYWppLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dC1zZWNyZXQtdmFsdWUteWltLWd3YWsta2ltLWplb24tNC0xLWplb24tam9uZy1zdXJsLTEK
  token-validity-in-seconds: 86400

# swagger setting
springdoc:
  swagger-ui:
    path: /api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha # 정렬 기준
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**